postgres:
  url: jdbc:postgresql://<HOST>:5432/grocery_sales
  user: <USER>
  password: 123

files:
  customers: /Grocery-Sales-data-pipeline//data/customers.csv
  products: /Grocery-Sales-data-pipeline/data/products.csv
  sales: /Grocery-Sales-data-pipeline//data/sales.csv
  